// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHCYjPVB99uYUymTIszI4vewQbBrGyH-s',
    appId: '1:18581242751:web:4b52e718568e405713504a',
    messagingSenderId: '18581242751',
    projectId: 'prayerapp-13c4f',
    authDomain: 'prayerapp-13c4f.firebaseapp.com',
    storageBucket: 'prayerapp-13c4f.appspot.com',
    measurementId: 'G-27LKKXPKTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp0WLVZ-xJek_iKaPgWEwSRyqW4n5gFwk',
    appId: '1:18581242751:android:3f504ab86052a7d213504a',
    messagingSenderId: '18581242751',
    projectId: 'prayerapp-13c4f',
    storageBucket: 'prayerapp-13c4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoMRu1loqkq_wohcvqDHc3abC0BVBe380',
    appId: '1:18581242751:ios:48b04727ffdb83f613504a',
    messagingSenderId: '18581242751',
    projectId: 'prayerapp-13c4f',
    storageBucket: 'prayerapp-13c4f.appspot.com',
    iosClientId: '18581242751-d3rbkkuh7avkoeav9pj35dt66gm997r0.apps.googleusercontent.com',
    iosBundleId: 'com.prayer.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoMRu1loqkq_wohcvqDHc3abC0BVBe380',
    appId: '1:18581242751:ios:8d8e7834e440f52613504a',
    messagingSenderId: '18581242751',
    projectId: 'prayerapp-13c4f',
    storageBucket: 'prayerapp-13c4f.appspot.com',
    iosClientId: '18581242751-qk8kkk2c7jergb3mlg96co53kochm7qi.apps.googleusercontent.com',
    iosBundleId: 'com.example.prayerMobilAppV2',
  );
}
